---
- name: Deploy monitoring system HTML
  hosts: webservers
  become: yes

  tasks:
          - name: install nginx
            apt:
                    name: nginx
                    state: present
                    update_cache: yes
          - name: copy html file to ngin
            copy:
                    src: index.html
                    dest: /var/www/html/index.html
                    owner: www-data
                    group: www-data
                    mode:'0644'
          - name: ensure nginx is running
            servcie:
                    name: nginx
                    state: running
                    enabled: yes

